/** Published dry-film reference processes. Values are recipe-specific, not intrinsic material constants. */
export const METAL_OXIDE_PRESETS = [
  {
    id: "vo2-chae-2006",
    family: "VO₂",
    name: "Vanadium tri-isopropoxide sol–gel",
    precursor: "0.12 M VO(OC₃H₇)₃ in isopropanol with acetic acid",
    substrate: "Sapphire",
    referenceThicknessNm: 96,
    referenceRpm: 2000,
    spinSeconds: 20,
    cycles: 3,
    thermalTreatment: "250 °C/3 min per coat; 410 °C/30 min in air, then low-pressure O₂ anneal above 400 °C",
    phase: "Monoclinic VO₂ after low-pressure O₂ anneal",
    evidence: "Three coats at approximately 32 nm per cycle",
    sourceUrl: "https://arxiv.org/abs/cond-mat/0510267",
  },
  {
    id: "tio2-zulkefle-2016",
    family: "TiO₂",
    name: "TTIP/acetic-acid sol–gel",
    precursor: "TTIP, ethanol, water, glacial acetic acid and Triton X-100",
    substrate: "ITO-coated glass",
    referenceThicknessNm: 22.87,
    referenceRpm: 3000,
    spinSeconds: 60,
    cycles: 1,
    thermalTreatment: "200 °C/10 min dry; 400 °C/15 min anneal",
    phase: "Annealed TiO₂; phase not specified for this thickness point",
    evidence: "Measured mean thickness in the published speed series",
    sourceUrl: "https://onlinelibrary.wiley.com/doi/10.1155/2016/9746156",
  },
  {
    id: "zno-khanali-2025",
    family: "ZnO",
    name: "Zinc acetate sol–gel",
    precursor: "Zinc acetate in ethanol with monoethanolamine",
    substrate: "Glass",
    referenceThicknessNm: 200,
    referenceRpm: 3000,
    spinSeconds: 10,
    cycles: 5,
    thermalTreatment: "250 °C after each coat; 450 °C/3 h in air",
    phase: "Nanocrystalline wurtzite ZnO",
    evidence: "Measured final thickness after five coats",
    sourceUrl: "https://doi.org/10.53063/synsint.2025.52268",
  },
  {
    id: "wo3-yano-2018",
    family: "WO₃",
    name: "Aqueous AMT/PVA sol–gel",
    precursor: "PVA:ammonium metatungstate:H₂O = 1:20:300 by weight",
    substrate: "Polished alumina",
    referenceThicknessNm: 50,
    referenceRpm: 2000,
    spinSeconds: 30,
    cycles: 1,
    thermalTreatment: "200 °C/10 min dry; 600 °C/2 h in air",
    phase: "Orthorhombic polycrystalline WO₃",
    evidence: "Approximately 50 nm by cross-sectional measurement",
    sourceUrl: "https://doi.org/10.3390/proceedings2130723",
  },
  {
    id: "fto-sankara-2007",
    family: "SnO₂:F",
    name: "Fluorine-doped tin oxide sol–gel",
    precursor: "Fluorine-doped SnO₂ sol–gel",
    substrate: "Glass",
    referenceThicknessNm: 350,
    referenceRpm: 3000,
    spinSeconds: 10,
    cycles: 8,
    thermalTreatment: "300 °C/15 min in air after each coat",
    phase: "Polycrystalline SnO₂:F",
    evidence: "Eight coats at approximately 45 nm per cycle",
    sourceUrl: "https://oam-rc.inoe.ro/articles/optoelectronic-properties-of-nanocrystalline-f-doped-sno2-fto-films-prepared-by-sol-gel-spin-coating-technique/fulltext",
  },
  {
    id: "hfo2-palm-2014",
    family: "HfO₂",
    name: "Hafnium-alkoxide dielectric sol–gel",
    precursor: "0.1 M hafnium alkoxide in 2-methoxyethanol",
    substrate: "Ti/Pt-coated borosilicate glass",
    referenceThicknessNm: 62,
    referenceRpm: 3000,
    spinSeconds: 30,
    cycles: 6,
    thermalTreatment: "150 °C/5 min per coat followed by three shaped photonic-curing pulses",
    phase: "Solution-processed HfO₂ dielectric",
    evidence: "Six coats measured at 71 nm before and 62 nm after photonic densification",
    sourceUrl: "https://doi.org/10.1016/j.ceramint.2014.07.099",
  },
  {
    id: "zro2-maleki-2020",
    family: "ZrO₂",
    name: "PEG-modified zirconyl sol–gel",
    precursor: "ZrOCl₂·8H₂O solution modified with PEG 400",
    substrate: "Silicon",
    referenceThicknessNm: 80,
    referenceRpm: 1200,
    spinSeconds: 30,
    cycles: 3,
    thermalTreatment: "150 °C/10 min per coat; 600 °C/1 h in air",
    phase: "Mixed monoclinic/tetragonal ZrO₂",
    evidence: "Measured final thickness after three coats",
    sourceUrl: "https://doi.org/10.3390/CIWC2020-06810",
  },
  {
    id: "in2o3-kul-2017",
    family: "In₂O₃",
    name: "Indium chloride sol–gel",
    precursor: "0.1 M InCl₃ in ethanol/HCl; 20 µL dispensed",
    substrate: "Microscope glass",
    referenceThicknessNm: 510,
    referenceRpm: 2500,
    spinSeconds: 20,
    cycles: 8,
    thermalTreatment: "100 °C/10 min dry; 425 °C/1 h in air after each coat",
    phase: "Single-phase polycrystalline cubic bixbyite In₂O₃",
    evidence: "Approximately 510 nm, digitized from the published coating-count graph",
    sourceUrl: "https://doi.org/10.21205/deufmd.2017195645",
  },
  {
    id: "ito-jafari-2014",
    family: "ITO",
    name: "PVA-assisted indium nitrate/tin chloride sol–gel",
    precursor: "0.5 M In(NO₃)₃·H₂O and SnCl₄ (In:Sn 90:10) with PVA, water, ethanol and HCl",
    substrate: "Glass",
    referenceThicknessNm: 120,
    referenceRpm: 2500,
    spinSeconds: 20,
    cycles: 5,
    thermalTreatment: "150 °C/20 min per coat; 500 °C/30 min in air, then 550 °C/1 h in Ar",
    phase: "Cubic In₂O₃-type ITO with Sn incorporated and no separate SnO₂ XRD phase",
    evidence: "120 nm by cross-sectional SEM after five ethanol/water-based coats",
    sourceUrl: "https://doi.org/10.1007/s40097-014-0089-y",
  },
];

export const METAL_OXIDE_FAMILIES = [...new Set(METAL_OXIDE_PRESETS.map(({ family }) => family))].sort();

export function filterMetalOxides(family = "") {
  return METAL_OXIDE_PRESETS.filter((preset) => !family || preset.family === family);
}
